/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.mw.totp_2fa.key.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import com.mw.totp_2fa.key.model.SecretKey;
import com.mw.totp_2fa.key.model.SecretKeyModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the SecretKey service. Represents a row in the &quot;totp_SecretKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SecretKeyModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SecretKeyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SecretKeyImpl
 * @generated
 */
public class SecretKeyModelImpl
	extends BaseModelImpl<SecretKey> implements SecretKeyModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a secret key model instance should use the <code>SecretKey</code> interface instead.
	 */
	public static final String TABLE_NAME = "totp_SecretKey";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"secretKeyId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"secretKey", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("secretKeyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("secretKey", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table totp_SecretKey (uuid_ VARCHAR(75) null,secretKeyId LONG not null primary key,companyId LONG,userId LONG,secretKey VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table totp_SecretKey";

	public static final String ORDER_BY_JPQL =
		" ORDER BY secretKey.secretKeyId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY totp_SecretKey.secretKeyId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long USERID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SECRETKEYID_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public SecretKeyModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _secretKeyId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSecretKeyId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _secretKeyId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return SecretKey.class;
	}

	@Override
	public String getModelClassName() {
		return SecretKey.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<SecretKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<SecretKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SecretKey, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((SecretKey)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<SecretKey, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<SecretKey, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(SecretKey)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<SecretKey, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<SecretKey, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<SecretKey, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<SecretKey, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<SecretKey, Object>>();

			attributeGetterFunctions.put("uuid", SecretKey::getUuid);
			attributeGetterFunctions.put(
				"secretKeyId", SecretKey::getSecretKeyId);
			attributeGetterFunctions.put("companyId", SecretKey::getCompanyId);
			attributeGetterFunctions.put("userId", SecretKey::getUserId);
			attributeGetterFunctions.put("secretKey", SecretKey::getSecretKey);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<SecretKey, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<SecretKey, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<SecretKey, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<SecretKey, String>)SecretKey::setUuid);
			attributeSetterBiConsumers.put(
				"secretKeyId",
				(BiConsumer<SecretKey, Long>)SecretKey::setSecretKeyId);
			attributeSetterBiConsumers.put(
				"companyId",
				(BiConsumer<SecretKey, Long>)SecretKey::setCompanyId);
			attributeSetterBiConsumers.put(
				"userId", (BiConsumer<SecretKey, Long>)SecretKey::setUserId);
			attributeSetterBiConsumers.put(
				"secretKey",
				(BiConsumer<SecretKey, String>)SecretKey::setSecretKey);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getSecretKeyId() {
		return _secretKeyId;
	}

	@Override
	public void setSecretKeyId(long secretKeyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secretKeyId = secretKeyId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalUserId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("userId"));
	}

	@Override
	public String getSecretKey() {
		if (_secretKey == null) {
			return "";
		}
		else {
			return _secretKey;
		}
	}

	@Override
	public void setSecretKey(String secretKey) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_secretKey = secretKey;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), SecretKey.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public SecretKey toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, SecretKey>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SecretKeyImpl secretKeyImpl = new SecretKeyImpl();

		secretKeyImpl.setUuid(getUuid());
		secretKeyImpl.setSecretKeyId(getSecretKeyId());
		secretKeyImpl.setCompanyId(getCompanyId());
		secretKeyImpl.setUserId(getUserId());
		secretKeyImpl.setSecretKey(getSecretKey());

		secretKeyImpl.resetOriginalValues();

		return secretKeyImpl;
	}

	@Override
	public SecretKey cloneWithOriginalValues() {
		SecretKeyImpl secretKeyImpl = new SecretKeyImpl();

		secretKeyImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		secretKeyImpl.setSecretKeyId(
			this.<Long>getColumnOriginalValue("secretKeyId"));
		secretKeyImpl.setCompanyId(
			this.<Long>getColumnOriginalValue("companyId"));
		secretKeyImpl.setUserId(this.<Long>getColumnOriginalValue("userId"));
		secretKeyImpl.setSecretKey(
			this.<String>getColumnOriginalValue("secretKey"));

		return secretKeyImpl;
	}

	@Override
	public int compareTo(SecretKey secretKey) {
		long primaryKey = secretKey.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof SecretKey)) {
			return false;
		}

		SecretKey secretKey = (SecretKey)object;

		long primaryKey = secretKey.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<SecretKey> toCacheModel() {
		SecretKeyCacheModel secretKeyCacheModel = new SecretKeyCacheModel();

		secretKeyCacheModel.uuid = getUuid();

		String uuid = secretKeyCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			secretKeyCacheModel.uuid = null;
		}

		secretKeyCacheModel.secretKeyId = getSecretKeyId();

		secretKeyCacheModel.companyId = getCompanyId();

		secretKeyCacheModel.userId = getUserId();

		secretKeyCacheModel.secretKey = getSecretKey();

		String secretKey = secretKeyCacheModel.secretKey;

		if ((secretKey != null) && (secretKey.length() == 0)) {
			secretKeyCacheModel.secretKey = null;
		}

		return secretKeyCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<SecretKey, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<SecretKey, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<SecretKey, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((SecretKey)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, SecretKey>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					SecretKey.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _secretKeyId;
	private long _companyId;
	private long _userId;
	private String _secretKey;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<SecretKey, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((SecretKey)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("secretKeyId", _secretKeyId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("secretKey", _secretKey);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("secretKeyId", 2L);

		columnBitmasks.put("companyId", 4L);

		columnBitmasks.put("userId", 8L);

		columnBitmasks.put("secretKey", 16L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private SecretKey _escapedModel;

}