/**
 * SPDX-FileCopyrightText: (c) 2025 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package com.mw.totp_2fa.key.model.impl;

import com.mw.totp_2fa.key.model.SecretKey;
import com.mw.totp_2fa.key.service.SecretKeyLocalServiceUtil;

/**
 * The extended model base implementation for the SecretKey service. Represents a row in the &quot;totp_SecretKey&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SecretKeyImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SecretKeyImpl
 * @see SecretKey
 * @generated
 */
public abstract class SecretKeyBaseImpl
	extends SecretKeyModelImpl implements SecretKey {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a secret key model instance should use the <code>SecretKey</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SecretKeyLocalServiceUtil.addSecretKey(this);
		}
		else {
			SecretKeyLocalServiceUtil.updateSecretKey(this);
		}
	}

}